config/routes.rb
Rails.application.routes.draw do
  resources :rooms, except: [:show]
  get '/', to: "rooms#index"
  get '/rooms', to: "rooms#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
  validates :title, :description, :beds, :guests, :image_url, presence: true
  validates :description, length: { maximum: 400 }
  validates :beds, numericality: { only_integer: true }
  # validates :price_per_night, numericality: { only_float: true }
  validates :guests, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to rooms_path
    else
      render :new
    end
  end

  def destroy
    roomdestroy = Room.find(params[:id])
    roomdestroy.destroy
    redirect_to rooms_path
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])

    if @room.update(room_params)
      redirect_to rooms_path, notice: "Modificado con exito"
    else
      render :edit
    end

  end

  protected
    def room_params
      params.require(:room).permit(:title, :description, :beds, :guests, :price_per_night, :image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>C9ia4hfhr6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:700|Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-2">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <a class="navbar-brand" href="#">AireCyD</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>


        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav">
            <li class="nav-item"><%= link_to "Habitaciones", rooms_path, class: "nav-link" %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <%= yield %>
  </body>
</html>

app/views/rooms/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>
        <%= @room.new_record? ? "Publicar": "Editar" %> Habitación</h1>

      <%= form_for @room do |f| %>
        <div class="form-group">
          <%= f.text_field :title, class: 'form-control input-lg', placeholder: "Título" %>
        </div>

        <div class="form-group">
          <%= f.text_area :description, class: 'form-control input-lg', placeholder: "Descripción" %>
        </div>

        <div class="form-group">
          <%= f.label :beds, "Número de Camas" %>
            <%= f.number_field :beds, class: 'form-control input-lg col-sm-2' %>
        </div>

        <div class="form-group">
          <%= f.label :guests, "Número de Huéspedes" %>
            <%= f.number_field :guests, class: 'form-control input-lg' %>
        </div>

        <div class="form-group">
          <%= f.label :price_per_night, "Precio por Noche" %>
            <%= f.number_field :price_per_night, class: 'form-control input-lg' %>
        </div>

        <div class="form-group">
          <%= f.text_field :image_url, class: 'form-control input-lg', placeholder: "URL de Imagen" %>
        </div>

        <div class="actions text-right">
          <%= f.submit @room.new_record? ? "Crear Habitación" : "Editar Habitación", class: "btn btn-primary btn-lg btn-block" %>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/rooms/edit.html.erb
<%= render 'form' %>

app/views/rooms/index.html.erb
<div class="container rooms">
  <div class="row">
    <div class="col-sm-12">
      <header>
        <h1>Habitaciones</h1>
        <%= link_to "<span class='glyphicon glyphicon-plus'></span><span class='hidden-xs'> Publicar </span>  Habitación".html_safe, new_room_path, class: "btn btn-primary new-room" %>
      </header>

      <div class="rooms-list">
      <% @rooms.each do |room| %>
        <div class="room">
          <div class="row">
            <div class="col-sm-5 col-md-4"><img src="<%= room.image_url %>"></div>
            <div class="col-sm-7 col-md-8">
              <div class="details clearfix">
                <h3><%= room.title %></h3>
                <div class="description"><%= room.description.truncate(255) if room.description %></div>
                <div class="number">
                  <div class="number-value"><%= room.beds %></div>
                  <div class="number-label">Camas</div>
                </div>
                <div class="number">
                  <div class="number-value"><%= room.price_per_night %></div>
                  <div class="number-label">Precio</div>
                </div>
                <div class="number">
                  <div class="number-value"><%= room.guests %></div>
                  <div class="number-label">Huéspedes</div>
                </div>
                <div class="actions">
                  <%= link_to "<span class='glyphicon glyphicon-pencil'><span>".html_safe, edit_room_path(room), class: "edit-room-btn" %>
                  <%= link_to "<span class='glyphicon glyphicon-trash'><span>".html_safe, room, method: :delete, data: { confirm: "¿Estás seguro de eliminar esta habitación?" }, class: "destroy-room-btn" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<%= render 'form' %>